### ISSUE TITLE
TODO in the project

### ISSUE THREAD

**Issue by JuliaGrasevych** [JuliaGrasevych/PhotoWeather#4]
- [x] Wrap SwiftUI vm input/output into struct
- [x] Request current user location
- [x] Use 3rd-party tool to generate project file
- [x] Write vm in Combine
- [x] Add icons, splash screen
- [x] Add dark/light themes
